### ISSUE TITLE
Server stuck eternally starting after trying to load Create Cobblemon

### ISSUE THREAD

**Issue by undeadbear13** [Lord-Of-Crumbs/Create-Cobblemon-Industrialized-Fabric-1.20.x#3]
here is a copy of the Server Log: https://pastebin.com/GC1SMGAp
for record it was working fine on previous update so its either a incompatibility with another mod, or something with the latest update of the mod, however it does work fully singleplayer so likely the later.
Once this happens the server will just sit there stuck in startup mode and will have to be manually shut down.

**Comment by jimmybenoit** [comment]
This is the same issue I was having. Posting my log with the mod isolated with just fabric api, create, and this create addon for added clarity.
https://pastebin.com/U4e2FHeQ

**Comment by ArsenicPurple** [comment]
I am having the same issue after updating. It loads perfectly fine on the client but serverside it comes back with the FluidRendererHandle error

**Comment by ArsenicPurple** [comment]
I made a temp version in which I just ripped out the fluid render registers and rebuilt it. Will work on the server but only on the server
[create_cobblemon-0.5-1.20.zip](https://github.com/user-attachments/files/18137660/create_cobblemon-0.5-1.20.zip)

**Comment by appe233** [comment]
OK, I've run into the same issue on my server. I tried it on my local machine and it worked fine. It just does not load on my server.
Also a problem with: `net.fabricmc.fabric.api.client.render.fluid.v1.FluidRenderHandler`

**Comment by Lord-Of-Crumbs** [comment]
Uploading hotfix now, please report if it fixes the issue.

**Comment by undeadbear13** [comment]
Hotfix seems to work, thank you!
