### ISSUE TITLE
Deployers Ignore incomplete Master ball Lid

### ISSUE THREAD

**Issue by someordinarydoom** [Lord-Of-Crumbs/Create-Cobblemon-Industrialized-Fabric-1.20.x#5]
Putting a shulker shell does get turned into an incomplete masterball lid using sand paper on a deployer, but then gets ignored on netherite ingots

**Comment by someordinarydoom** [comment]
i now see that it may be that it's still using the pure shulker shell and not the incompleter masterball lid for the recipie on the sequenced assembly

**Comment by Lord-Of-Crumbs** [comment]
ohh wait I see the issue, I'll upload a hotfix in a bit

**Comment by Lord-Of-Crumbs** [comment]
Issue fixed with hotfix that was just uploaded.
