### ISSUE TITLE
Harvesters don't harvest berries

### ISSUE THREAD

**Issue by Shytora** [Lord-Of-Crumbs/Create-Cobblemon-Industrialized-Fabric-1.20.x#7]
Harvesters destroy and replant fully grown berries, but they don't actually harvest anything.
Edit: I am on v0.4 still, unsure if it's fixed in the "0.5.2 hotfix" version.

**Comment by Lord-Of-Crumbs** [comment]
This is not a feature that we claim to implement. If you would like to, instead, suggest this as a feature, remake this, clarify and reframe it as a suggestion.
